"""Generate Scripts/icondex.lua, the item id to icon name table.

Palworld keeps item icons in one folder, named T_itemicon_<Category>_<ItemId>:

    /Game/Others/InventoryItemIcon/Texture/T_itemicon_Material_CopperIngot

The item id is the tail, but the category in the middle is not derivable from
the id, so an icon cannot be addressed without knowing it. This walks the
shipped pak and records the pairing.

The pak's directory index is compressed, so only names embedded in
uncompressed asset data are visible here and the result is a good subset
rather than the whole set. That is why icons.lua keeps runtime fallbacks: this
table makes the common case instant, it does not make it complete.

    python tools/gen_icondex.py
"""

import io
import os
import re
import sys

PAK = (r"C:\Program Files (x86)\Steam\steamapps\common\Palworld"
       r"\Pal\Content\Paks\Pal-Windows.pak")
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "Scripts", "icondex.lua")

PREFIX = "T_itemicon_"
PATTERN = re.compile(rb"T_itemicon_[A-Za-z0-9_]+")

CHUNK = 64 * 1024 * 1024
OVERLAP = 256          # so a name split across two chunks is still seen


def scan(path):
    names = set()
    size = os.path.getsize(path)
    done = 0
    tail = b""

    with io.open(path, "rb") as handle:
        while True:
            block = handle.read(CHUNK)
            if not block:
                break

            for match in PATTERN.finditer(tail + block):
                names.add(match.group().decode("ascii"))

            tail = block[-OVERLAP:]
            done += len(block)
            sys.stderr.write("\r  %5.1f%%  %d names" %
                             (100.0 * done / size, len(names)))
            sys.stderr.flush()

    sys.stderr.write("\n")
    return names


def main():
    if not os.path.exists(PAK):
        print("pak not found: " + PAK)
        return 2

    print("scanning " + PAK)
    names = scan(PAK)

    # Keyed by the id lowercased, because the ids come from a data table at
    # runtime and matching case exactly is a promise this cannot keep.
    table = {}
    for name in sorted(names):
        rest = name[len(PREFIX):]
        if "_" not in rest:
            # A handful carry no category at all, so the whole tail is the id.
            key = rest.lower()
        else:
            key = rest.split("_", 1)[1].lower()

        # First wins, and sorting above makes "first" stable across runs
        # rather than whatever order the file happened to yield.
        if key and key not in table:
            table[key] = rest

    lines = [
        "-- Item id to icon name, generated by tools/gen_icondex.py.",
        "--",
        "-- Do not edit by hand. Palworld names every item icon",
        "-- T_itemicon_<Category>_<ItemId> and keeps them all in one folder,",
        "-- but the category cannot be worked out from the id, so it has to be",
        "-- recorded. This is read from the shipped pak.",
        "--",
        "-- Incomplete on purpose rather than by accident: the pak's index is",
        "-- compressed and only part of it is readable from outside the",
        "-- engine. icons.lua falls back to the running game for the rest.",
        "",
        "local M = {}",
        "",
        'M.FOLDER = "/Game/Others/InventoryItemIcon/Texture/"',
        "",
        "M.NAMES = {",
    ]
    for key in sorted(table):
        lines.append('    ["%s"] = "%s",' % (key, table[key]))
    lines.append("}")
    lines.append("")
    lines.append("return M")
    lines.append("")

    with io.open(OUT, "wb") as handle:
        handle.write("\r\n".join(lines).encode("utf-8"))

    print("wrote %d entries to %s" % (len(table), OUT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
